// packages/luna-svelte/src/component/slot/SlotBase.svelte
<script lang="ts" module>
  import type { Column, Field as FieldType, Style } from '@luna-form/core'
  import type { Component, Snippet } from 'svelte'
  import type { Children } from '../../type'

  export type ColumnProps = {
    children?: Snippet
    column?: Column
  }

  export type FieldProps = {
    children: Children
    disabled?: boolean
    errors?: Record<string, string[]>
    field: FieldType
    style?: Style
  }
</script>

<script lang="ts">
  import { isColumn, isField, prepare, type Fields } from '@luna-form/core'
  import SlotBase from './SlotBase.svelte'

  let {
    children,
    components,
    disabled,
    fields,
    style,
  }: {
    children: Children
    components: {
      column: Component<ColumnProps>
      field: Component<FieldProps>
    }
    disabled?: boolean
    fields?: Fields
    style?: Style
  } = $props()

  const preparedFields = $derived(prepare(fields))
</script>

{#each preparedFields as field, index (index)}
  {#if isColumn(field)}
    <components.column column={field}>
      <SlotBase
        {children}
        {components}
        {disabled}
        fields={field.fields}
        {style}
      />
    </components.column>
  {:else if isField(field)}
    <components.field {disabled} {field} {style} {children} />
  {/if}
{/each}

// packages/luna-react/src/component/slot/slot-base.tsx
import { isColumn, isField, prepare, type Fields } from '@luna-form/core'
import { Fragment } from 'react'
import type { Children } from '../../type'
import type { ColumnProps } from '../column'
import type { FieldProps } from '../field/field'
import type { Style } from '../../lib/use-style'

export function SlotBase<
  T extends {
    column: React.ComponentType<ColumnProps>
    field: React.ComponentType<FieldProps>
  },
>(
  props: Readonly<{
    children: Children
    disabled?: boolean
    fields?: Fields
    components: T
    style?: Style
  }>
) {
  const fields = prepare(props.fields)

  const { column: Column, field: Field } = props.components

  return fields.map((field, index) => (
    <Fragment key={index}>
      {isColumn(field) && (
        <Column column={field} style={props.style}>
          <SlotBase {...props} fields={field.fields} />
        </Column>
      )}
      {isField(field) && (
        <Field disabled={props.disabled} field={field}>
          {props.children}
        </Field>
      )}
    </Fragment>
  ))
}
