// packages/luna-react/src/component/field/field-error.tsx
import type { Nullable } from '@luna-form/core'

export function FieldError(
  props: Readonly<{
    errors?: Nullable<string[]>
    name?: string
  }>
) {
  if (!props.errors || props.errors.length === 0) {
    return null
  }

  return (
    <ul
      className="text-sm text-red-600 dark:text-red-500"
      id={props.name ? `${props.name}-error` : undefined}
    >
      {props.errors?.map((error, index) => (
        <li key={props.name ? `${props.name}-error-${index}` : index}>
          {error}
        </li>
      ))}
    </ul>
  )
}

// packages/luna-svelte/src/component/field/FieldError.svelte
<script lang="ts">
  import type { Nullable } from '@luna-form/core'

  let {
    errors,
    name,
  }: {
    errors?: Nullable<string[]>
    name?: string
  } = $props()
</script>

{#if errors && errors.length > 0}
  <ul
    class="text-sm text-red-600 dark:text-red-500"
    id={name ? `${name}-error` : undefined}
  >
    {#each errors as error, index (name ? `${name}-error-${index}` : index)}
      <li>
        {error}
      </li>
    {/each}
  </ul>
{/if}
