// packages/luna-react/src/component/field.tsx
import { FieldGroup } from './field-group'
import { InputBase } from './input/input-base'
import { buildDisabled, buildOrientation, type Field } from '@luna-form/core'
import type { Children } from '../type'

export type FieldProps = Readonly<{
  children: Children
  disabled?: boolean
  errors?: Record<string, string[]>
  field: Field
  withinColumn?: boolean
}>

export function Field(props: FieldProps) {
  const cols = props.field.advanced?.cols
  const errors = props.field.name ? props.errors?.[props.field.name] : undefined

  const orientation = buildOrientation(props.field)
  const disabled = buildDisabled(props.field, props.disabled)

  return (
    <FieldGroup
      cols={cols}
      disabled={disabled}
      errors={errors}
      orientation={orientation}
    >
      <InputBase
        disabled={disabled}
        errors={errors}
        field={props.field}
        withinColumn={props.withinColumn}
      >
        {props.children}
      </InputBase>
    </FieldGroup>
  )
}

// packages/luna-svelte/src/component/field/Field.svelte
<script lang="ts">
  import {
    buildDisabled,
    buildOrientation,
    mergeStyle,
    type Field as FieldType,
    type Style,
  } from '@luna-form/core'
  import FieldError from './FieldError.svelte'
  import FieldGroup from './FieldGroup.svelte'
  import InputBase from '../input/InputBase.svelte'
  import type { Snippet } from 'svelte'
  import type {
    AriaAttributes,
    CommonProps,
    DataAttributes,
    Orientation,
  } from '@luna-form/core'

  type ChildrenSnippet = Snippet<
    [
      {
        ariaAttributes: AriaAttributes
        commonProps: CommonProps
        dataAttributes: DataAttributes
        field: FieldType
        orientation?: Orientation
      },
    ]
  >

  let {
    children,
    disabled,
    errors,
    field,
    style,
  }: {
    children: ChildrenSnippet
    disabled?: boolean
    errors?: Record<string, string[]>
    field: FieldType
    style?: Style
  } = $props()

  const cols = $derived(field.advanced?.cols)
  const fieldErrors = $derived(field.name ? errors?.[field.name] : undefined)

  const mergedStyle = $derived(
    mergeStyle(style, {
      orientation: buildOrientation(field),
    })
  )

  const orientation = $derived(mergedStyle.orientation)
  const derivedDisabled = $derived(buildDisabled(field, disabled))
</script>

<div class="flex flex-col gap-3">
  <FieldGroup
    {cols}
    disabled={derivedDisabled}
    errors={fieldErrors}
    {field}
    {orientation}
  >
    <InputBase
      disabled={derivedDisabled}
      errors={fieldErrors}
      {field}
      {orientation}
      {children}
    />
  </FieldGroup>
  <FieldError errors={fieldErrors} name={field.name} />
</div>
