// packages/luna-react/src/client/component/field/field-set.tsx
import { FieldSetAdvanced } from './field-set-advanced'
import { FieldSetBase } from '../../../component/field/field-set-base'
import { Group } from '../../../component/group'
import {
  mergeStyle,
  translateOptional,
  type Section,
  type Style,
} from '@luna-form/core'

export function FieldSet(
  props: Readonly<{
    advanced?: {
      step?: boolean
    }
    children?: React.ReactNode
    section: Section
    step?: number
    style?: Style
    translations?: Record<string, string>
  }>
) {
  const { fields = [] } = props.section

  const step = props.advanced?.step ? props.step : undefined
  const { compact } = mergeStyle(props.style, {
    compact: props.section.advanced?.compact,
  })

  const group = <Group compact={compact}>{props.children}</Group>
  if (!props.section.title && !props.section.description) {
    return group
  }

  const title = translateOptional(props.section.title, props.translations)
  const description = translateOptional(
    props.section.description,
    props.translations
  )

  if (props.section.advanced?.collapsible) {
    return (
      <FieldSetAdvanced
        description={description}
        group={group}
        section={props.section}
        title={title}
      />
    )
  }

  return (
    <FieldSetBase
      description={description}
      empty={fields.length === 0}
      id={props.section.id?.toString()}
      step={step}
      title={title}
    >
      {group}
    </FieldSetBase>
  )
}

// packages/luna-svelte/src/component/field/FieldSet.svelte
<script lang="ts">
  import Group from '../Group.svelte'
  import Legend from '../Legend.svelte'
  import { mergeStyle, type Section, type Style } from '@luna-form/core'
  import type { Snippet } from 'svelte'

  let {
    children,
    section,
    style,
  }: {
    children?: Snippet
    section: Section
    style?: Style
  } = $props()

  const fields = $derived(section.fields || [])

  const mergedStyle = $derived(
    mergeStyle(style, {
      compact: section.compact,
    })
  )

  const compact = $derived(mergedStyle.compact)
</script>

{#if !section.title && !section.description}
  <Group {compact}>
    {#if children}
      {@render children()}
    {/if}
  </Group>
{:else}
  <fieldset
    data-slot="field-set"
    data-empty={fields.length === 0}
    class="flex flex-col data-[empty=false]:gap-6"
    id={section.id?.toString()}
  >
    <Legend description={section.description} title={section.title} />
    <Group {compact}>
      {#if children}
        {@render children()}
      {/if}
    </Group>
  </fieldset>
{/if}
