// packages/luna-react/src/component/field/field-set.tsx
import { Group } from '../group'
import { Legend } from '../legend'
import { mergeStyle, type Section, type Style } from '@luna-form/core'

export function FieldSet(
  props: Readonly<{
    children?: React.ReactNode
    section: Section
    style?: Style
  }>
) {
  const fields = props.section.fields || []

  const { compact } = mergeStyle(props.style, {
    compact: props.section.compact,
  })

  if (!props.section.title && !props.section.description) {
    return <Group compact={compact}>{props.children}</Group>
  }

  return (
    <fieldset
      data-slot="field-set"
      data-empty={fields.length === 0}
      className="flex flex-col data-[empty=false]:gap-6"
      id={props.section.id?.toString()}
    >
      <Legend
        description={props.section.description}
        title={props.section.title}
      />
      <Group compact={compact}>{props.children}</Group>
    </fieldset>
  )
}

// packages/luna-svelte/src/component/field/FieldSet.svelte
<script lang="ts">
  import Group from '../Group.svelte'
  import Legend from '../Legend.svelte'
  import { mergeStyle, type Section, type Style } from '@luna-form/core'
  import type { Snippet } from 'svelte'

  let {
    children,
    section,
    style,
  }: {
    children?: Snippet
    section: Section
    style?: Style
  } = $props()

  const fields = $derived(section.fields || [])

  const mergedStyle = $derived(
    mergeStyle(style, {
      compact: section.compact,
    })
  )

  const compact = $derived(mergedStyle.compact)
</script>

{#if !section.title && !section.description}
  <Group {compact}>
    {#if children}
      {@render children()}
    {/if}
  </Group>
{:else}
  <fieldset
    data-slot="field-set"
    data-empty={fields.length === 0}
    class="flex flex-col data-[empty=false]:gap-6"
    id={section.id?.toString()}
  >
    <Legend description={section.description} title={section.title} />
    <Group {compact}>
      {#if children}
        {@render children()}
      {/if}
    </Group>
  </fieldset>
{/if}
