// packages/luna-react/src/component/field/field-group.tsx
import {
  VERTICAL,
  isCheckbox,
  isClickable,
  type Field,
  type Orientation,
} from '@luna-form/core'
import { FieldVertical } from './field-vertical'
import { FieldHorizontal } from './field-horizontal'

export function FieldGroup(
  props: Readonly<{
    children: React.ReactNode
    cols?: number
    disabled?: boolean
    errors?: string[]
    field: Field
    orientation?: Orientation
  }>
) {
  const clickable = isClickable(props.field)
  const checkbox = isCheckbox(props.field)

  if (props.orientation === VERTICAL) {
    return (
      <FieldVertical
        cols={props.cols}
        disabled={props.disabled}
        errors={props.errors}
        isCheckbox={checkbox}
        isClickable={clickable}
      >
        {props.children}
      </FieldVertical>
    )
  }

  return (
    <FieldHorizontal
      cols={props.cols}
      disabled={props.disabled}
      errors={props.errors}
      isCheckbox={checkbox}
      isClickable={clickable}
    >
      {props.children}
    </FieldHorizontal>
  )
}

// packages/luna-svelte/src/component/field/FieldGroup.svelte
<script lang="ts">
  import {
    VERTICAL,
    isCheckbox as checkIsCheckbox,
    isClickable as checkIsClickable,
    type Field,
    type Orientation,
  } from '@luna-form/core'
  import type { Snippet } from 'svelte'
  import FieldVertical from './FieldVertical.svelte'
  import FieldHorizontal from './FieldHorizontal.svelte'

  let {
    children,
    cols,
    disabled,
    errors,
    field,
    orientation,
  }: {
    children?: Snippet
    cols?: number
    disabled?: boolean
    errors?: string[]
    field: Field
    orientation?: Orientation
  } = $props()

  const isClickable = $derived(checkIsClickable(field))
  const isCheckbox = $derived(checkIsCheckbox(field))
</script>

{#if orientation === VERTICAL}
  <FieldVertical {cols} {disabled} {errors} {isCheckbox} {isClickable}>
    {#if children}
      {@render children()}
    {/if}
  </FieldVertical>
{:else}
  <FieldHorizontal {cols} {disabled} {errors} {isCheckbox} {isClickable}>
    {#if children}
      {@render children()}
    {/if}
  </FieldHorizontal>
{/if}
