// packages/luna-svelte/src/component/field/Field.svelte
<script lang="ts">
  import {
    buildDisabled,
    buildOrientation,
    getSpan,
    mergeStyle,
    type Field as FieldType,
    type Style,
  } from '@luna-form/core'
  import { twMerge } from 'tailwind-merge'
  import FieldError from './FieldError.svelte'
  import FieldGroup from './FieldGroup.svelte'
  import InputBase from '../input/InputBase.svelte'
  import type { Snippet } from 'svelte'
  import type {
    AriaAttributes,
    CommonProps,
    DataAttributes,
  } from '@luna-form/core'

  type ChildrenSnippet = Snippet<
    [
      {
        ariaAttributes: AriaAttributes
        commonProps: CommonProps
        dataAttributes: DataAttributes
        field: FieldType
        horizontal?: boolean
      },
    ]
  >

  let {
    children,
    disabled,
    errors,
    field,
    style,
  }: {
    children: ChildrenSnippet
    disabled?: boolean
    errors?: Record<string, string[]>
    field: FieldType
    style?: Style
  } = $props()

  const cols = $derived(field.advanced?.cols)
  const fieldErrors = $derived(field.name ? errors?.[field.name] : undefined)

  const mergedStyle = $derived(
    mergeStyle(style, {
      horizontal: buildOrientation(field),
    })
  )

  const horizontal = $derived(mergedStyle.horizontal)
  const derivedDisabled = $derived(buildDisabled(field, disabled))
</script>

<div class={twMerge('flex flex-col gap-3', getSpan(cols))}>
  <FieldGroup
    disabled={derivedDisabled}
    errors={fieldErrors}
    {field}
    {horizontal}
  >
    <InputBase
      disabled={derivedDisabled}
      errors={fieldErrors}
      {field}
      {horizontal}
      {children}
    />
  </FieldGroup>
  <FieldError errors={fieldErrors} name={field.name} />
</div>

// packages/luna-react/src/component/field/field.tsx
import { FieldError } from './field-error'
import { FieldGroup } from './field-group'
import { InputBase } from '../input/input-base'
import {
  buildDisabled,
  buildOrientation,
  getSpan,
  mergeStyle,
  type Field,
  type Style,
} from '@luna-form/core'
import { twMerge } from 'tailwind-merge'
import type { Children } from '../../type'

export type FieldProps = Readonly<{
  children: Children
  disabled?: boolean
  errors?: Record<string, string[]>
  field: Field
  style?: Style
}>

export function Field(props: FieldProps) {
  const cols = props.field.advanced?.cols
  const errors = props.field.name ? props.errors?.[props.field.name] : undefined

  const { horizontal } = mergeStyle(props.style, {
    horizontal: buildOrientation(props.field),
  })

  const disabled = buildDisabled(props.field, props.disabled)

  return (
    <div className={twMerge('flex flex-col gap-3', getSpan(cols))}>
      <FieldGroup
        disabled={disabled}
        errors={errors}
        field={props.field}
        horizontal={horizontal}
      >
        <InputBase
          disabled={disabled}
          errors={errors}
          field={props.field}
          horizontal={horizontal}
        >
          {props.children}
        </InputBase>
      </FieldGroup>
      <FieldError errors={errors} name={props.field.name} />
    </div>
  )
}
