// packages/luna-svelte/src/component/slot/Slot.svelte
<script lang="ts">
  import Field from '../field/Field.svelte'
  import Column from '../Column.svelte'
  import SlotBase from './SlotBase.svelte'
  import type { Fields, Style } from '@luna-form/core'
  import type { Children } from '../../type'

  let {
    children,
    disabled,
    fields,
    style,
  }: {
    children: Children
    disabled?: boolean
    fields?: Fields
    style?: Style
  } = $props()
</script>

<SlotBase
  {children}
  {disabled}
  {fields}
  {style}
  components={{ column: Column, field: Field }}
/>

// packages/luna-react/src/client/component/slot.tsx
import { Column } from '../../component/column'
import { Field } from './wrapper'
import { SlotBase } from '../../component/slot/slot-base'
import type { Children } from '../../type'
import type { Fields, Style } from '@luna-form/core'

export const Slot = (
  props: Readonly<{
    children: Children
    disabled?: boolean
    fields?: Fields
    style?: Style
  }>
) => <SlotBase {...props} components={{ column: Column, field: Field }} />
