// packages/luna-svelte/src/component/Column.svelte
<script lang="ts">
  import { getColumn } from '@luna-form/core'
  import type { Column } from '@luna-form/core'
  import type { Snippet } from 'svelte'
  import { twMerge } from 'tailwind-merge'

  let {
    children,
    column,
  }: {
    children?: Snippet
    column?: Column
  } = $props()

  const cols = $derived(getColumn(column?.advanced?.cols))
</script>

<div class="flex w-full flex-col gap-4">
  <div class={twMerge('grid grid-cols-1 gap-3 sm:gap-4', cols)}>
    {#if children}
      {@render children()}
    {/if}
  </div>
</div>

// packages/luna-react/src/component/column.tsx
import { getColumn, type Column } from '@luna-form/core'
import { twMerge } from 'tailwind-merge'

export function Column(
  props: Readonly<{
    children?: React.ReactNode
    column?: Column
  }>
) {
  const cols = getColumn(props.column?.advanced?.cols)

  return (
    <div className="flex w-full flex-col gap-4">
      <div className={twMerge('grid grid-cols-1 gap-3 sm:gap-4', cols)}>
        {props.children}
      </div>
    </div>
  )
}
