// packages/luna-svelte/src/component/Form.svelte
<script lang="ts">
  import Control from './Control.svelte'
  import FieldSet from './field/FieldSet.svelte'
  import Group from './Group.svelte'
  import Separator from './Separator.svelte'
  import { prepare, type Definition, type Sections } from '@luna-form/core'
  import type { Config, Control as ControlType, Slot } from '../type'

  let {
    action,
    children,
    config,
    control,
    definition,
    isPending,
    noValidate,
    readOnly,
    sections: sectionsProp,
  }: {
    action?: string | ((formData: FormData) => void)
    children: Slot
    config: Config
    control?: ControlType
    definition?: Definition
    isPending?: boolean
    noValidate?: boolean
    readOnly?: boolean
    sections: Sections
  } = $props()

  const sections = $derived(prepare(sectionsProp, definition))
</script>

<div class="h-full w-full">
  <form novalidate={noValidate} action={action as any}>
    <Group>
      {#each sections as section}
        <FieldSet {section} style={config.style}>
          {@render children({
            disabled: readOnly,
            fields: section.fields,
          })}
        </FieldSet>
        {#if section.separator}
          <Separator />
        {/if}
      {/each}
      {#if control}
        <Control {isPending} children={control} />
      {/if}
    </Group>
  </form>
</div>

// packages/luna-react/src/component/form.tsx
import { Control } from './control'
import { FieldSet } from './field/field-set'
import { Fragment } from 'react'
import { Group } from './group'
import { Separator } from './separator'
import { prepare, type Definition, type Sections } from '@luna-form/core'
import type { Config, Slot } from '../type'

export function Form(
  props: Readonly<{
    action?: (formData: FormData) => void
    children: Slot
    config: Config
    control?: React.ReactNode
    definition?: Definition
    noValidate?: boolean
    readOnly?: boolean
    sections: Sections
  }>
) {
  const sections = prepare(props.sections, props.definition)

  return (
    <div className="h-full w-full">
      <form noValidate={props.noValidate} action={props.action}>
        <Group>
          {sections.map((section, index) => (
            <Fragment key={index}>
              <FieldSet section={section}>
                {props.children({
                  disabled: props.readOnly,
                  fields: section.fields,
                })}
              </FieldSet>
              {section.separator && <Separator />}
            </Fragment>
          ))}
          {props.control && <Control>{props.control}</Control>}
        </Group>
      </form>
    </div>
  )
}
