// packages/luna-react/src/component/control.tsx
import type { Control } from '../type'

export function Control(
  props: Readonly<{
    children?: Control
    isPending?: boolean
  }>
) {
  const content =
    typeof props.children === 'function'
      ? props.children({ isPending: props.isPending })
      : props.children

  return (
    <div data-slot="field-control" className="w-full">
      {content}
    </div>
  )
}

// packages/luna-svelte/src/component/Control.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  let {
    children,
    isPending,
  }: {
    children?: Snippet<[{ isPending?: boolean }]>
    isPending?: boolean
  } = $props()
</script>

<div data-slot="field-control" class="w-full">
  {#if children}
    {@render children({ isPending })}
  {/if}
</div>
