// packages/luna-react/src/component/group.tsx
export function Group(
  props: Readonly<{
    children?: React.ReactNode
    compact?: boolean
  }>
) {
  return (
    <div
      data-slot="field-group"
      data-compact={props.compact}
      className="flex w-full flex-col gap-8 data-[compact=true]:gap-3"
    >
      {props.children}
    </div>
  )
}

// packages/luna-svelte/src/component/Group.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { twMerge } from 'tailwind-merge'

  let {
    children,
    compact,
  }: {
    children?: Snippet
    compact?: boolean
  } = $props()
</script>

<div
  data-slot="field-group"
  data-compact={compact}
  class={twMerge('flex w-full flex-col gap-8 data-[compact=true]:gap-3')}
>
  {#if children}
    {@render children()}
  {/if}
</div>
