// packages/luna-react/src/component/input-group.tsx
import { FormattedDescription } from './formatted-description'
import { InputLabel } from './input-label'
import type { Config } from '../type'
import type { Field } from '@luna-form/core'

export function InputGroup(
  props: Readonly<{
    children: React.ReactNode
    config?: Config
    context?: Record<string, unknown>
    field: Field
    horizontal?: boolean
    translations?: Record<string, string>
  }>
) {
  return (
    <>
      {props.field.name && props.field.label && (
        <InputLabel
          config={props.config}
          context={props.context}
          field={props.field}
          horizontal={props.horizontal}
          translations={props.translations}
        />
      )}
      {props.children}
      {props.horizontal === false && (
        <FormattedDescription
          config={props.config}
          context={props.context}
          text={props.field.description}
          translations={props.translations}
        />
      )}
    </>
  )
}

// packages/luna-svelte/src/component/InputGroup.svelte
<script lang="ts">
  import { translate, type Field } from '@luna-form/core'
  import FormattedDescription from './FormattedDescription.svelte'
  import InputLabel from './InputLabel.svelte'
  import type { Config } from '../type.js'
  import type { Snippet } from 'svelte'

  let {
    children,
    config,
    context,
    field,
    horizontal,
    translations,
  }: {
    children?: Snippet
    config?: Config
    context?: Record<string, unknown>
    field: Field
    horizontal?: boolean
    translations?: Record<string, string>
  } = $props()
</script>

{#if field.name && field.label}
  <InputLabel {config} {context} {field} {horizontal} {translations} />
{/if}

{#if children}
  {@render children()}
{/if}

{#if !horizontal && field.description}
  <FormattedDescription text={translate(field.description, translations)} />
{/if}
