// packages/luna-react/src/component/input-label.tsx
import { FormattedDescription } from './formatted-description'
import { Label } from './label'
import {
  HORIZONTAL,
  interpolate,
  isInterpolated,
  translate,
  type Field,
  type Orientation,
} from '@luna-form/core'
import type { Config } from '../type'

export function InputLabel(
  props: Readonly<{
    config?: Config
    context?: Record<string, unknown>
    field: Field
    orientation?: Orientation
    translations?: Record<string, string>
  }>
) {
  const label = isInterpolated(props.field.label)
    ? interpolate(props.field.label, {
        context: props.context,
        env: props.config?.env,
      })
    : props.field.label

  const description = isInterpolated(props.field.description)
    ? interpolate(props.field.description, {
        context: props.context,
        env: props.config?.env,
      })
    : props.field.description

  return (
    <div
      data-slot="field-content"
      className="flex w-full flex-1 flex-col gap-1.5 leading-snug"
    >
      <Label field={props.field}>{translate(label, props.translations)}</Label>
      {props.orientation === HORIZONTAL && (
        <FormattedDescription
          text={translate(description, props.translations)}
        />
      )}
    </div>
  )
}

// packages/luna-svelte/src/component/InputLabel.svelte
<script lang="ts">
  import {
    HORIZONTAL,
    interpolate,
    isInterpolated,
    translate,
  } from '@luna-form/core'
  import FormattedDescription from './FormattedDescription.svelte'
  import Label from './Label.svelte'
  import type { Config } from '../type.js'
  import type { Field, Orientation } from '@luna-form/core'

  let {
    config,
    context,
    field,
    orientation,
    translations,
  }: {
    config?: Config
    context?: Record<string, unknown>
    field: Field
    orientation?: Orientation
    translations?: Record<string, string>
  } = $props()

  const label = $derived(
    isInterpolated(field.label)
      ? interpolate(field.label, {
          context,
          env: config?.env,
        })
      : field.label
  )

  const description = $derived(
    isInterpolated(field.description)
      ? interpolate(field.description, {
          context,
          env: config?.env,
        })
      : field.description
  )
</script>

<div
  data-slot="field-content"
  class="flex w-full flex-1 flex-col gap-1.5 leading-snug"
>
  <Label {field} {translations}>
    {translate(label, translations)}
  </Label>
  {#if orientation === HORIZONTAL}
    <FormattedDescription text={translate(description, translations)} />
  {/if}
</div>
