// packages/luna-react/src/component/label.tsx
import {
  isCheckbox,
  isRadio,
  translate,
  type Field,
} from '@luna-form/core'
import { twMerge } from 'tailwind-merge'

export function Label(
  props: Readonly<{
    children?: React.ReactNode
    field: Field
    translations?: Record<string, string>
  }>
) {
  const normal = isRadio(props.field) || isCheckbox(props.field)

  return (
    <label
      data-slot="field-label"
      data-normal={normal}
      className={twMerge(
        'flex w-fit items-center gap-2 text-sm leading-snug font-medium select-none',
        'data-[normal=true]:font-normal',
        'group-data-[readonly=true]:cursor-not-allowed group-data-[readonly=true]:opacity-50'
      )}
      htmlFor={props.field.name}
    >
      {props.children}
      {!props.field.required && (
        <span className="text-sm text-slate-600 dark:text-slate-400">
          {translate('(Optional)', props.translations)}
        </span>
      )}
    </label>
  )
}

// packages/luna-svelte/src/component/Label.svelte
<script lang="ts">
  import { isCheckbox, isRadio, translate } from '@luna-form/core'
  import type { Field } from '@luna-form/core'
  import { twMerge } from 'tailwind-merge'

  let {
    field,
    translations,
  }: {
    field: Field
    translations?: Record<string, string>
  } = $props()

  const normal = $derived(isRadio(field) || isCheckbox(field))
</script>

<label
  data-slot="field-label"
  data-normal={normal}
  class={twMerge(
    'flex w-fit items-center gap-2 text-sm leading-snug font-medium select-none',
    'data-[normal=true]:font-normal',
    'group-data-[readonly=true]:cursor-not-allowed group-data-[readonly=true]:opacity-50'
  )}
  for={field.name}
>
  <slot />
  {#if !field.required}
    <span class="text-sm text-slate-600 dark:text-slate-400">
      {translate('(Optional)', translations)}
    </span>
  {/if}
</label>
